[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mf_quant_engine"
version = "0.1.0"
description = "Production Quantitative Engine for Mutual Funds"
dependencies = [
    "pandas", "numpy", "sqlalchemy", "prophet",
    "streamlit", "pydantic-settings", "pymysql", "pyarrow"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]